### PR TITLE
Fix Sidebar Overlap of menu items and footer 

### LINKED ISSUE #86: [BUG]: Dashboard SideBar Responsiveness issue
## Description
In few Screen sizes , the dashboard sidebar content collapsed with each other.

image

## Steps to Reproduce
1. Login to the Dashboard.
2. Check the UI of Dashboard in different screen sizes to populate the issue.

## Expected Behavior
Collided content should be aligned properly. Dashboard Sidebar should look similar to the below screenshot:

image

## Possible Solution
Need to fix the required styles in the sidebar component for alignment issues in all the screen resolution.

### PR DESCRIPTION
**Pull request by UtkarshDixit-py**
Fixes #86 
- Changed the sidebar layout to use a "Flex" container with a "column" direction to better structure the sidebar's menu items and footer.
- Implemented a "VStack" to manage the vertical spacing.
- Adjusted the "SideBarFooter" component to remove absolute positioning.

### CODE REVIEW

**Comment by UtkarshDixit-py** [comment]
@macintushar Let me know if you want me to add scroll function in sidebar.
[multiwovenissue86.webm](https://github.com/Multiwoven/multiwoven-ui/assets/60638489/a56b807d-714a-4ab3-bd49-f3331b5968fd)

**Review by macintushar — APPROVED** [review]
Looks good to me @UtkarshDixit-py

**Comment by macintushar** [comment]
@UtkarshDixit-py the base branch should be `develop` and not `main`. Have changed it but there's a merge conflict, please resolve ti.

**Comment by UtkarshDixit-py** [comment]
@macintushar Will take care next time, Thanks

**Comment by sumitd94** [comment]
@UtkarshDixit-py prettier checks are failing - https://github.com/Multiwoven/multiwoven-ui/actions/runs/8183998565/job/22396892640?pr=98

**Comment by UtkarshDixit-py** [comment]
@sumitd94 I have updated it. Please check

**Review by sumitd94 — APPROVED** [review]

**Pull request merged**
